# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- group: "Secrets"

trigger:
- main

stages:
  - stage: Checking_Coverage
    displayName: Build
    jobs:
      - template: ./check-coverage.yml
        parameters:
          Platform: Windows
      - template: ./check-coverage.yml
        parameters:
          Platform: Mac
