# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- group: "Secrets"

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- powershell: 
  workingDirectory: $(Build.SourcesDirectory)
  displayName: Upload coverage report to Coveralls
  targetType: 'filePath'
  filePath: run-coveralls-coverage.ps1
  arguments: -COVERALLS_REPO_TOKEN $env:CoverallsToken
  env:
    CoverallsToken: $(CoverallsToken)
